kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  privileged: true
  
  
  environment:
    GOOS: linux
    GOARCH: ppc64le
    DOCKER_CLI_EXPERIMENTAL: enabled
  
 
  volumes:
    - name: cache
      path: /tmp/cache
  commands:
  - docker buildx version
  - docker buildx create --driver docker-container --use
  - docker buildx create --platform linux/arm64,linux/arm/v8,linux/ppc64le --name test
  
  - docker tag test  sbm13/multiarch-test:latest
  - docker push sbm13/multiarch-test:latest
  - docker buildx ls
  
volumes:
- name: cache
  host:
    path: /var/lib/cache
