kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
- name: Buildx
  image: docker:20
  variables:
     DOCKER_DRIVER: overlay2
  volumes:
    - name: docker socket
      path: /var/run/docker.sock
  commands:
  - docker buildx build  --platform linux/ppc64le  -t sbm13/multiarch-test:latest  --push  .
