kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  variables:
    DOCKER_HOST: tcp://docker:2375/
    DOCKER_DRIVER: overlay2
    DOCKER_TLS_CERTDIR: ""

  
  privileged: true
  environment:
    GOOS: linux
    GOARCH: ppc64le
    DOCKER_CLI_EXPERIMENTAL: enabled
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock:unix:///var/run/docker.sock
  commands:
 
  - docker buildx version
  - docker buildx create --driver docker-container --use
  - docker buildx create --platform linux/arm64,linux/arm/v8,linux/ppc64le
  - docker login -u sbm13 -p Sbm@1396
  - docker buildx build  -t  test -f Dockerfile . 
  - docker tag test  sbm13/multiarch-test:latest
  - docker push sbm13/multiarch-test:latest
  - docker buildx ls
