name: amd64
kind: pipeline
type: docker

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!
  
---
name: arm64
kind: pipeline
type: docker

platform:
  os: linux
  arch: arm64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!
---

