kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:

- name: Buildx
  image: docker:20
  volumes:
    - name: docker socket
      path: /var/run/docker.sock  
  commands:
  - curl --unix-socket /var/run/docker.sock http://localhost/version
  - docker buildx ls
