kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  privileged: true
  environment:
    GOOS: linux
    GOARCH: ppc64le
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock:/var/run/docker.sock
  commands:
 
  -  docker buildx version
  - docker login -u sbm13 -p Sbm@1396
  - docker buildx build --load --platform linux/ppc64le -t sbm13/multiarch-test:latest --push .
  - docker buildx ls
