kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
---
kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
---
kind: pipeline
type: docker
name: ppc64le

platform:
  os: linux
  arch: ppc64le
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
