kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:

- name: Buildx
  image: plugins/docker
  volumes:
    - name: docker socket
      path: /var/run/docker.sock
  
  commands:
  - docker install buildx
  - docker buildx ls
