kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  privileged: true
  environment:
    GOOS: linux
    GOARCH: ppc64le
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock:/var/run/docker.sock
  commands:
 
  -  docker buildx version
  - docker buildx create --use --name mybuild node-amd64
  - docker buildx ls
