kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
---
kind: pipeline
type: docker
name: amdd64

platform:
  os: linux
  arch: arm64
steps:
- name: docker buildx
  image: docker:20
  commands:
  - docker login
  - docker buildx build -t test -f Dockerfile .
  - docker tag test sbm13/test1
  - docker push sbm13/test
  - echo "It worked!"
  
