kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
---

kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64
steps:
- name: Install Qemu
  image: tonistiigi/binfmt
  commands:
  - docker buildx create --use --name mybuild node-amd64
  - docker buildx create --append --name mybuild node-arm64
  - docker buildx build --platform linux/amd64,linux/arm64 .
- name: test
  image: alpine
  commands:
  - echo "It worked!"


