kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"

kind: pipeline
type: docker
name: arm64

platform:
  os: linux
  arch: arm64
steps:
- name: checkout code
  image: actions/checkout@v2

- name: test
  image: alpine
  commands:
  - echo "It worked!"


