kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  experimental: true
  privileged: true
  environment:
    GOOS: linux
    GOARCH: ppc64le
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock:/var/run/docker.sock
  commands:
 
  - docker buildx version
  - docker buildx create --driver docker-container --use
  - docker buildx create --platform linux/arm64,linux/arm/v8
  - docker buildx build  --platform linux/ppc64le -t  test  .
  - docker tag test  sbm13/multiarch-test:latest
  - docker push sbm13/multiarch-test:latest
  - docker buildx ls
