kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
- name: Buildx
  image: docker:20
  volumes:
    - name: docker socket
      path: /var/run/docker.sock
  commands:
  - docker run  --volume=/var/run/docker.sock:/var/run/docker.sock --rm --privileged multiarch/qemu-user-static:register
  - docker buildx create --use --name mybuild node-amd64
  - docker buildx create --append --name mybuild node-arm64
  - docker buildx build --platform linux/arm64 .
