kind: pipeline
type: docker
name: default

steps:

- name: Buildx
  image: docker:19
  privileged: true
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
  
  
  environment:
    GOOS: linux
    GOARCH: ppc64le
    DOCKER_CLI_EXPERIMENTAL: enabled
  
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock

  commands:
  - docker buildx version
  - docker buildx create --driver docker-container --use
  - docker buildx create --platform linux/arm64,linux/arm/v8,linux/ppc64le --name test
  - docker tag test  sbm13/multiarch-test:latest
  - docker push sbm13/multiarch-test:latest
  - docker buildx ls
  
volumes:
- name: docker socket
  host:
    path: /var/run/docker.sock

