kind: pipeline
type: docker
name: amd64

steps:

- name: Buildx
  image: docker:20
  
  

  environment:
    GOOS: linux
    GOARCH: ppc64le
    DOCKER_CLI_EXPERIMENTAL: enabled
 
  volumes:
    - name: docker socket
      path: /var/run/docker.sock:unix:///var/run/docker.sock
  commands:
  - docker version
  
