kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:

- name: Buildx
  image: plugins/docker
  
  commands:
  - apt show qemu-system-x86
  - docker buildx build  --platform linux/ppc64le  -t sbm13/multiarch-test:latest  --push  .
