kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
- name: Buildx
  image: docker:20
  volumes:
    - name: docker socket
      path: /var/run/docker.sock
  commands:
  - docker buildx create --use --name mybuild node-amd64
  - docker buildx create --append --name mybuild node-arm64
  - docker buildx build --platform linux/amd64,linux/arm64 .
