kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
- name: Buildx
  image: docker:20
  volumes:
    - name: docker socket
      path: /var/run/docker.sock
  commands:
  - docker run --privileged --rm tonistiigi/binfmt --install all
