kind: pipeline
type: docker
name: amd64

platform:
  os: linux
  arch: amd64
steps:
- name: test
  image: alpine
  commands:
  - echo "It worked!"
- name: Buildx
  image: docker:20
  volumes:
    - name: docker socket
      path: /var/run/docker.sock
  commands:

  - cat /proc/sys/fs/binfmt_misc/qemu-amd64
